name: Deploy Static Site to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload files to Blob Storage
        run: |
          az storage blob upload-batch \
            --account-name medicsite410056 \
            --destination '$web' \
            --source .